//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC6.Models
{
    using System;
    using System.Collections.Generic;
	using System.ComponentModel;
	using System.ComponentModel.DataAnnotations;
	using System.Web.Mvc;

	public partial class EmployeeData
    {	
		[HiddenInput(DisplayValue =false)]
        public int Id { get; set; }
		[DisplayAttribute(Name = "Full name")]
		public string FullName { get; set; }
		[DisplayFormat(NullDisplayText = "Gender not specify")]
        public string Gender { get; set; }
        public int Age { get; set; }
		[DisplayFormat(DataFormatString ="{0:d}")]
		[UIHint("DateWithCalender")]
		public System.DateTime HireDate { get; set; }
		[DataType(DataType.EmailAddress)]
		[ReadOnly(true)]
        public string EmailAddress { get; set; }
		[ScaffoldColumn(false)]
		[DataType(DataType.Currency)]
        public int Salary { get; set; }
		[DataType(DataType.Url)]
		[UIHint("OpenInNewWindow")]
        public string PersonalWebsite { get; set; }
    }
}
